# Generated by Django 4.1.4 on 2023-01-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.TextField()),
                ('next_move', models.TextField()),
                ('name', models.TextField()),
                ('wdl', models.CharField(max_length=100)),
            ],
        ),
    ]
